version: 2.1

jobs:
  sayhello:
    description: A job that says Hello
    machine: true
    steps:
      - run: echo "Hello World!"
  sayhelloMP:
    description: Une job qui dit Hello Marie-Pier
    machine: true
    steps:
      - run: echo "Hello Marie-Pier"
  displayFiles:
    description: Une job qui affiche les fichiers
    machine: true
    steps:
      - run: ls -al

workflows:
  monWorkflow:
    jobs:
      - sayhello
      - displayFiles:
          requires:
            - sayhello
      - sayhelloMP:
          requires:
            - sayhello
